[tool.poetry]
name = "neovim-venv"
version = "0.1.0"
description = ""
authors = ["FOX"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
neovim = "^0.3.1"
pynvim = "^0.5.0"
cmakelint = "^1.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
